language: php

php:
    - 5.5
    - 5.6
    - hhvm
    - nightly

allow_failures:
    - php: nightly

env:
    - TWIG_EXT=no
    - TWIG_EXT=yes

before_script:
    - if [ "$TWIG_EXT" == "yes" ]; then sh -c "cd ext/twig && phpize && ./configure --enable-twig && make && sudo make install"; fi
    - if [ "$TWIG_EXT" == "yes" ]; then echo "extension=twig.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]; then sed -i.bak "s|vendor/autoload.php|test/bootstrap.php|" phpunit.xml.dist; fi

install:
    # Composer is not available on PHP 5.2
    - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]; then travis_retry composer install; fi

install:
  - travis_retry composer install --no-interaction

matrix:
    exclude:
        - php: hhvm
          env: TWIG_EXT=yes
        - php: nightly
          env: TWIG_EXT=yes
